### ISSUE TITLE
Additional properties for components

### ISSUE THREAD

**Issue by milkeshaa** [instructure/instructure-ui#707] opened 2021-09-06 13:22 UTC
### Context

Components: **Tabs**, **Tabs.Panel**, **Modal** (**Mask** which is a child of **Modal** one).

### Summary

Requested functionality:
1. Please, add _height_ property to **Tabs** and **Tabs.Panel** components. 
  **Tabs** component does not have its own _height_ property, but when it's provided it's passed through **View** component which is the origin of the **Tabs** component. Could you add this property to **Tabs** component as well.
  **Tabs.Panel** also does not have its own _height_ property, I want to ask you to make it available and when provided to be applied to the div element which is the origin of the **Tabs.Panel** component and to the **View** component which is inside of this div element.  
  
2. Please, add _overflowX_ and _overflowY_ properties to **Tabs.Panel** component.
  **Tabs.Panel** also does not have its own _overflowX_ and _overflowY_ properties, I want to ask you to make them available and when provided to be applied to the **View** component which is inside of **Tabs.Panel** component. 
  
3. Please, make it possible to change _flexDirection_ property of the origin component of the **Modal** one (**Mask** component).
  Currently it's set to 'row' by default, but it seems like there is no possibility to change it.
  
### Justification

  Because sometimes it is necessary to match the _height_ of the parent element, so that the child elements of the **Tabs.Panel** component also have the opportunity to expand in _height_. Especially when you are using elements with absolute position as children of the **Tabs.Panel** component (just for example). So while using heights we should be able to manipulate _overflow_ (hide it or show it and so on). 
  Adding posibility to change _flexDirection_ is also important, since we should be able to change the direction of expanding the **Modal** component HTML element (with row direction it can only expand horizontally).

### Additional Details

  It's very important to implement this functionality, since that currently when you need to set these properties for these components you have no other way except traversing and manipulating DOM elements using JavaScript.

**Comment by Brailor** [comment] 2021-09-06 14:05
Hi there!

Thank you for your feedback/suggestions!
We will look into them and get back to you with a more detailed response, however this could take us a while to do, so please bear with us.

**Comment by Brailor** [comment] 2021-09-08 09:27
Hi, just a quick update, we are going to discuss these suggestions today with the design team to see if they are feasible.
In the meantime could you tell me which version of inst-ui are you using?

**Comment by milkeshaa** [comment] 2021-09-08 11:59
Hi, thanks for informing me! 
We are using the latest version (8.8.0) of inst-ui.

Yes, here are some examples with comments in them:

-  **With Tabs & Tabs.Panel components:**
https://codepen.io/milkeshaa/pen/PojWOGv

- **With Modal component**
https://codepen.io/milkeshaa/pen/BaZpJbm

**Comment by milkeshaa** [comment] 2021-09-08 16:25
After reviewing the solution for the **Modal** component again, we came to the conclusion that there are no problems with this component.

So, no additional properties for this component are needed, thanks :)

**Comment by Brailor** [comment] 2021-09-21 06:59
Hi, we've made a PR: #716 
We also expanded the documentation of the Tabs component with examples showcasing how you can control the size of the component.
Could you please check 'Controlling the size and the spacing' sections examples to verify that the proposed change will satisfy your needs?

https://6148506ca3ea2d7af40c7641--preview-instui.netlify.app/#Tabs -> 'Controlling the size and the spacing'

**Comment by milkeshaa** [comment] 2021-09-22 09:03
Hello, seems like everything is okay about controlling the size and the spacing, but what about overflow? It seems to me, that when we have fixed height property we may obtain situations when overflow will appear and I think that we should have the possibility to hide it.

**Comment by ke1k0** [comment] 2021-09-27 11:56
Hi @milkeshaa!

Sorry for the late answer.

We decided not to add the overflow property, because it doesn't seem to be a common (or encouraged) situation where one would want to hide the overflow of the content. Also, in case it is absolutely needed, it can be easily achieved by wrapping the content of the panel in a `div` with a style `height: 100%; overflow: hidden;`.

We would like to avoid adding props to our components that add functionality that wouldn't support our design system, and/or would cause problems with accessibility, and/or can be achieved without the prop too. 

Does the PR @Brailor linked provide a solution for you problem? May I merge and release it?

**Comment by milkeshaa** [comment] 2021-09-27 12:52
Yes, thank you

**Comment by ke1k0** [comment] 2021-09-28 14:06
Hi @milkeshaa ! InstUI [v8.10.0](https://instructure.design/#CHANGELOG) has been released, including this feature too. I'm closing this ticket, but let us know if you have any further problems!

**Closed by ke1k0** 2021-09-28 14:06 UTC

**Comment by milkeshaa** [comment] 2021-09-30 09:11
Hello @ke1k0, @Brailor! Previously I was testing this new functionality in Chrome browser and everything works great, but recently I checked it in Safari and found that the collapse of an element is still happening... Seems like div elements with class postfix __panelsContainer should have height 100% or flex-basis 100% as well... Some piece of advice? Should I create a new issue or is it a problem somewhere on my side? 
Waiting for your answer. Thank you!

**Comment by ke1k0** [comment] 2021-09-30 09:25
Hi @milkeshaa! I'm sorry to hear it is still not working. If I open our example in Safari ([Controlling the size and the spacing section](https://instructure.design/#Tabs/#controlling-the-size-and-the-spacing)), the `fixHeight: 100%` option seems to work. Could you please send us a codepen where you can reproduce the error?

**Comment by milkeshaa** [comment] 2021-09-30 09:36
@ke1k0 thanks for the quick answer! Yes, here is an example based on my previous example, but with using fixHeight: https://codepen.io/milkeshaa/pen/vYZPKWM

**Comment by ke1k0** [comment] 2021-09-30 11:03
Hm, this is strange, opening your codepen in Safari seems to work fine for me. What version of Safari are you using? I tried it with Version 14.1.2 (16611.3.10.1.6) (and Big Sur).

**Comment by milkeshaa** [comment] 2021-09-30 11:06
@ke1k0 for a test I was using Cataling 13.1. And now I double-checked it in Big Sur 14.1 and yes, everything works great here.

**Comment by ke1k0** [comment] 2021-09-30 11:14
I see, thanks for checking it. InstUI supports the last 2 major versions of the main browsers, and since Safari v15 came out a few days ago, technically speaking we don't support v13 anymore :) If you need it to work in 13 as well, we can have a look at it next week, maybe we find a quick fix for this. Let us know whether having it work on v14+ is sufficient for you, or you need to support v13 as well!

**Comment by milkeshaa** [comment] 2021-09-30 11:20
Okay, I will let you know soon. Thanks for the quick answers and your help!
