### ISSUE TITLE
"Element is not defined" with Nextjs

### ISSUE THREAD

**Issue by SimonVanherweghe** [instructure/instructure-ui#1135] opened 2022-12-09 15:26 UTC
### Question
I would like to use Instructure-ui in Nextjs

As [stated in the documentation for SSR](https://instructure.design/#server-side-rendering), I need to substitute Element from the DOM API. I've done this [in the _app.js file](https://github.com/SimonVanherweghe/nextjs-instructure-ui/blob/05a82af964389e22b79c7045f99f870fc69050e6/pages/_app.js#L3), although I'm not entirely sure if I did it right.

It seems like Portal is the one that's causing issues, when I run `npm ls @instructure/ui-portal` to see which package depends on it, I only get `ui-select`.
The strange thing is: the `ui-select` component renders fine. But the `AppNav` (in Nav, which is in Layout) is also causing issues.

What is going on here? How can I substitute Element in the right way?

### Code Sample
I've created a minimal project that isolates the problem here: https://github.com/SimonVanherweghe/nextjs-instructure-ui

**Comment by Brailor** [comment] 2022-12-13 10:53
Hi @SimonVanherweghe!

Thanks for the issue report and the repro project!
After some testing, it does not seem like you did anything wrong. The issue is not really clear to me at this point, but I will investigate about it and report back to you.

**Comment by Brailor** [comment] 2023-03-10 09:48
Fixed in: https://github.com/instructure/instructure-ui/pull/1168

**Closed by Brailor** 2023-03-10 09:48 UTC
