### ISSUE TITLE
Warning: [Focusable] Exactly one focusable child is required (0 found).

### ISSUE THREAD

**Issue by maxpluez** [instructure/instructure-ui#109] opened 2020-08-21 00:06 UTC
I've been trying to use Tabs for my components. The Tabs seem to be working fine with its focusable features (focus onto the selection bar and then select with arrow keys), but I keep getting the warning shown in the title. Here's the JSX for the component:

```jsx
<View>
      {error && <ErrorAlert err={error.err} msg={error.msg} />}
      <Tabs onRequestTabChange={handleTabChange}>
        <Tabs.Panel
          id="bruincast"
          renderTitle={`${
            constants.mediaTypeMap.get(constants.MEDIA_TYPE.BRUINCAST).string
          } (${bruincastCount})`}
          isSelected={tabSelectedIndex === constants.TABS.BRUINCAST}
        >
          <Bruincast
            course={course}
            warning={warning}
            retrieveWarning={retrieveWarning}
            userid={userid}
            setError={setError}
          />
        </Tabs.Panel>
        {videoReservesTabEnabled() && (
          <Tabs.Panel
            id="videoReserves"
            renderTitle={`${
              constants.mediaTypeMap.get(constants.MEDIA_TYPE.VIDEO_RESERVES)
                .string
            } (${videoReserveCount})`}
            isSelected={tabSelectedIndex === constants.TABS.VIDEO_RESERVES}
          >
            <VideoReserve
              course={course}
              onCampus={onCampusStatus}
              userid={userid}
              setError={setError}
            />
          </Tabs.Panel>
        )}
        <Tabs.Panel
          id="audioReserves"
          renderTitle={`${
            constants.mediaTypeMap.get(
              constants.MEDIA_TYPE.DIGITAL_AUDIO_RESERVES
            ).string
          } (${audioReserveCount})`}
          isSelected={
            tabSelectedIndex ===
            constants.TABS.DIGITAL_AUDIO_RESERVES -
              (!videoReservesTabEnabled() ? 1 : 0) // Reindex if VideoReserve tab is hidden
          }
        >
          <MusicReserve userid={userid} setError={setError} />
        </Tabs.Panel>
        <Tabs.Panel
          id="mediaGallery"
          renderTitle={
            constants.mediaTypeMap.get(constants.MEDIA_TYPE.MEDIA_GALLERY)
              .string
          }
          isSelected={
            tabSelectedIndex ===
            constants.TABS.MEDIA_GALLERY - (!videoReservesTabEnabled() ? 1 : 0) // Reindex if VideoReserve tab is hidden
          }
        >
          Media Gallery
        </Tabs.Panel>
        {adminPanel}
      </Tabs>
    </View>
```

**Comment by chrisguerrero** [comment] 2020-08-24 20:00
@maxpluez I'd start with a fresh sandbox and import the InstUI components you're using without any of your custom components or business logic. That would help isolate the issue so you can reproduce what's going on.

**Comment by HerrTopi** [comment] 2020-11-18 15:21
Since this is only a minor inconvenience for developers we are closing this issue

**Closed by HerrTopi** 2020-11-18 15:21 UTC
