### ISSUE TITLE
Changing theme prop based on state

### ISSUE THREAD

**Issue by kubilayagi** [instructure/instructure-ui#102] opened 2020-08-04 19:56 UTC
Hi all,

This perhaps isn't an issue with instructure-ui, but I'm relatively new to React and I thought this would be a good place to ask this question. I am building a table that acts as a form for a course builder for our school. Each of the rows has a checkbox to indicate that the course should be built when the checkbox is selected and vice versa. I'm using the theme prop to add custom styling to the highlighted rows ( #99 ), but I want to be able to change the theme back to the default depending on whether the checkbox is checked or not. I am trying to combine #99 with [this code sandbox example](https://codesandbox.io/s/wizardly-bell-uju2h), but it doesn't seem like instructure-ui supports custom styling via the className prop.

How I have it laid out (roughly to spare some complexity) is like this:

```
const courseStyling = {
        'selected': { background: 'lightblue', },
        'unselected': { background: 'white', },
};

const [coursesData, setCoursesData] = React.useState(courses);

const toggleToBeBuilt = (course, index) => {
        // ... change course data accordingly ...
        let updatedCourseData = courseData;
        course.toBeBuilt = !course.toBeBuilt;
        updatedCourseData[index] = course;
        setCoursesData(updatedCourseData);
        return null;
};

const courseListings = coursesData.map((course, index) => (
        <Table.Row key={index}>
            <Table.Cell theme={courseStyling[course.toBeBuilt === true ? 'selected' : 'unselected']}>data</Table.Cell>
            <Table.Cell theme={courseStyling[course.toBeBuilt === true ? 'selected' : 'unselected']}>
                <Checkbox onChange={() => toggleToBeBuilt(course, index)}></Checkbox>
            </Table.Cell>
        </Table.Row>
);

return (
    <Table>
        <Table.Head> ........ </Table.Head>
        <Table.Body>{courseListings}</Table.Body>
    </Table>
);
```

In its current state, the themes show up when the table is first rendered, but when i uncheck the checkbox, the theme doesn't change. I've verified that the courseData object is updated correctly. Based on that sandbox example I linked above, it would seem like the theme should change, but it seems to work differently with the theme prop than with the className prop.

If anyone has any suggestions for solutions or better places to ask this question, I'd really appreciate it! Thanks in advance

**Comment by ke1k0** [comment] 2020-12-01 17:30
Hi!

Thank you for the code sample!

I found the issue in the code: in your `toggleToBeBuilt` method you are modifying the original `coursesData` array, so it doesn't trigger an app rerender (with `let updatedCourseData = coursesData` they point to the same array). 

One way to solve the problem is to make a copy of the `coursesData` array like with the spread operator:
```js
let updatedCourseData = [ ...coursesData ]
```

You could also use the `map` method to make it shorter (and prevent reassigning parameters, which may cause side effects in general). This way it creates a copy of the original courses array too, overwriting the course concerned in the same step:
```js
const toggleToBeBuilt = (course, index) => {
    const updatedCourseData = coursesData.map((course, courseIndex) => {
      return index === courseIndex
        ? { ...course, toBeBuilt: !course.toBeBuilt }
        : course;
    });
    setCoursesData(updatedCourseData);
    return null;
  };
```

I hope I could help! I'm closing this issue now, but if you still have any questions or these two methods doesn't solve your problem, feel free to leave a comment or reopen the issue. Thanks!

**Closed** 2020-12-01 17:30 UTC
Labels: 1, Question
